import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import fetch from 'node-fetch';
import { BeerList } from '../components/beer-list/beer-list'

export type Beer = {
  name: string;
  tagline	: string;
  description: string;
  id: number;
  image_url: string;
  abv: number;
};

const Home: NextPage<{ beers: Beer[] }> = ({ beers }) => {

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="center">
          Welcome to Beers
        </h1>
        <BeerList name="Headliner Beer" beers={beers} />

      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch(`https://api.punkapi.com/v2/beers?per_page=8`)
  const beers = await res.json()

  if (!beers) {
    return {
       notFound: true,
    }
 }

 return {
    props: {
      beers
    }, 
 }
};

export default Home


